[phases.setup]
nixPkgs = ["python3", "gcc", "libffi", "openssl", "pkg-config"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[phases.start]
cmds = ["uvicorn app.main:app --host=0.0.0.0 --port=8000"]
