[phases.setup]
nixPkgs = ["python3", "gcc", "libffi", "openssl", "pkg-config"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt",
  "chmod +x /app/start.sh"
]

[phases.start]
cmds = ["/app/start.sh"]
